# Namespace
namespace: robot-shop

# Ingress web
ingress:
  host: robot-shop.at.lab

# Registry and repository for Docker images
image:
  imagePullSecrets: robot-shop-image-secrets
  repository: alfian8
  cartTag: latest
  catalogueTag: latest
  dispatchTag: latest
  mongodbTag: latest
  mysqlTag: latest
  paymentTag: latest
  rabbitmqTag: 3.8-management-alpine
  ratingsTag: latest
  redisTag: 6.2-alpine
  shippingTag: latest
  userTag: latest
  webTag: latest

# EUM configuration
# Provide your key and set the endpoint
eum:
  key: null
  url: https://eum-eu-west-1.instana.io

# Pod Security Policy
psp:
  enabled: false

payment:
    # Alternative payment gateway URL
    # Default is https://www.paypal.com
    gateway: null

# NodePort for web service
nodeport: true

persistentStorage:
  storageClass: nfs-dev-provisioner
  requests: 3Gi