apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch
  namespace: {{ .Values.namespace }}
  labels:
    service: dispatch
spec:
  replicas: 1
  selector:
    matchLabels:
      service: dispatch
  template:
    metadata:
      labels:
        service: dispatch
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      containers:
      - name: dispatch
        image: {{ .Values.image.repository }}/rs-dispatch:{{ .Values.image.dispatchTag }}
        imagePullPolicy: Always
        env:
          # agent networking access
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
      imagePullSecrets:
      - name: {{ .Values.image.imagePullSecrets }}