apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.persistentStorage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistentStorage.requests }}