apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: {{ .Values.namespace }}
  labels:
    service: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        service: mysql
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      containers:
      - name: mysql
        image: {{ .Values.image.repository }}/rs-mysql-db:{{ .Values.image.mysqlTag }}
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: mysql-secret
        # added for Istio
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
        resources:
          limits:
            cpu: 400m
            memory: 1200Mi
          requests:
            cpu: 200m
            memory: 800Mi
      restartPolicy: Always
      imagePullSecrets:
      - name: {{ .Values.image.imagePullSecrets }}
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim