apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: {{ .Values.namespace }}
  labels:
    service: payment
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: payment