apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: {{ .Values.namespace }}
  labels:
    service: ratings
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    service: ratings