apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: redis
  name: redis
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis
  serviceName: redis
  template:
    metadata:
      labels:
        service: redis
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      containers:
      - name: redis
        image: {{ .Values.image.repository }}/redis:{{ .Values.image.redisTag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
        volumeMounts:
          - name: redis-persistent-storage
            mountPath: /var/lib/redis
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
      imagePullSecrets:
      - name: {{ .Values.image.imagePullSecrets }}
      volumes:
      - name: redis-persistent-storage
        persistentVolumeClaim:
          claimName: redis-pv-claim