apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: {{ .Values.namespace }}
  labels:
    service: web
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: web
  {{ if .Values.nodeport }}
  type: NodePort
  {{ end }}